# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f44dd8e7e0e8e888559c47e77b06c303f16c5f0df4ddce095c459cb18932c8d91c0997682bc740ada62862762ffd5265e41979a6aede0ae37a2faf554da20f

test:
  secret_key_base: 34f44dd8e7e0e8e888559c47e77b06c303f16c5f0df4ddce095c459cb18932c8d91c0997682bc740ada62862762ffd5265e41979a6aede0ae37a2faf554da20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 34f44dd8e7e0e8e888559c47e77b06c303f16c5f0df4ddce095c459cb18932c8d91c0997682bc740ada62862762ffd5265e41979a6aede0ae37a2faf554da20f
